### ISSUE TITLE
User can add students - Model

### ISSUE THREAD

**Issue by krlenell** [krlenell/tutor-tracker-api#1]
Student:
```
student_id: uuid
student_name: text
is_active: boolean (default false)
is_minor: boolean
student_phone: int (can be null)
student_email: text (can be null)
school: text (can be null)
address: text(can be null)
```

would like to ensure student has phone and email if not minor.  think this would be done at model level?

**Comment by krlenell** [comment]
Am I an idiot? where are fields for parent's names, emails, phone numbers, etc

**Comment by thebearingedge** [comment]
in a `guardians` table like you mentioned 👍

**Comment by krlenell** [comment]
can add custom validation to model that student must have phone/email if not minor
similarly, can add validation to model that student has guardian if minor

**Comment by krlenell** [comment]
Need to add phone and email custom validations, probably use `ActiveModel::EachValidator` as they will be used across multiple tables/ models

**Comment by krlenell** [comment]
Need to create a valid phone-generator method and pass it into factorybot
